// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-n-X63HgtLHQq9l86NnyOufZMn4U_QA',
    appId: '1:913566234493:web:4978ff1a59417ece5c7e14',
    messagingSenderId: '913566234493',
    projectId: 'midnight-app-31012026',
    authDomain: 'midnight-app-31012026.firebaseapp.com',
    storageBucket: 'midnight-app-31012026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyvFPx9Yhkkk8OpfpKk-F_ywfFn2rJODs',
    appId: '1:913566234493:android:c2418ff95894675d5c7e14',
    messagingSenderId: '913566234493',
    projectId: 'midnight-app-31012026',
    storageBucket: 'midnight-app-31012026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXat8Tij-BQ5G-vBRMnNpGc9vJ-gFGPE',
    appId: '1:913566234493:ios:6a0bc36ac6cc69765c7e14',
    messagingSenderId: '913566234493',
    projectId: 'midnight-app-31012026',
    storageBucket: 'midnight-app-31012026.firebasestorage.app',
    iosBundleId: 'com.midnight.app.midnightApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXat8Tij-BQ5G-vBRMnNpGc9vJ-gFGPE',
    appId: '1:913566234493:ios:6a0bc36ac6cc69765c7e14',
    messagingSenderId: '913566234493',
    projectId: 'midnight-app-31012026',
    storageBucket: 'midnight-app-31012026.firebasestorage.app',
    iosBundleId: 'com.midnight.app.midnightApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-n-X63HgtLHQq9l86NnyOufZMn4U_QA',
    appId: '1:913566234493:web:0e668ce31dca48495c7e14',
    messagingSenderId: '913566234493',
    projectId: 'midnight-app-31012026',
    authDomain: 'midnight-app-31012026.firebaseapp.com',
    storageBucket: 'midnight-app-31012026.firebasestorage.app',
  );
}
